on:
    workflow_dispatch:

jobs:
    test-my-action:
        name: Test the action
        runs-on: ubuntu-latest
        steps:
            - name: Summarise SVS-SBOMs
              id: summary
              uses: hoeppner-dataport/summarise-svs-sboms@878e288f16f32be59bd19b12dd668a7874df7f06
              with:
                  filename: dependencies.sbom.json
                  repos: hpi-schul-cloud/tldraw-server:999.6.6;hpi-schul-cloud/schulcloud-client:999.6.6;hpi-schul-cloud/schulcloud-server:999.6.6

            - name: work with json
              run: echo '${{ toJson(steps.summary.outputs.json) }}'
