on:
    workflow_dispatch:

jobs:
    test-my-action:
        name: Test the action
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              uses: hoeppner-dataport/summarise-svs-sboms@68a6a3a788267ff5a368fe6f8e42c05d4e11d060
              with:
                  filename: dependencies.sbom.json
                  repos: |-
                      hpi-schul-cloud/schulcloud-client:999.6.6
                      hpi-schul-cloud/tldraw-server:999.6.6
                      hpi-schul-cloud/schulcloud-server:999.6.6
